apiVersion: s3.ceph.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: test-bucket-1
spec:
  providers:
    - ceph-admin-cfg
  forProvider:
    acl: private
    objectLockEnabledForBucket: true
  providerConfigRef:
    name: ceph-admin-cfg